# Generated by Django 4.1 on 2022-10-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopqna',
            fields=[
                ('qnanum', models.AutoField(primary_key=True, serialize=False, verbose_name='qna번호')),
                ('user_id', models.CharField(max_length=30, verbose_name='작성자')),
                ('qnatitle', models.CharField(max_length=200, verbose_name='글 제목')),
                ('qnacontent', models.TextField(verbose_name='글 내용')),
                ('qnareadcount', models.IntegerField(default=0, verbose_name='조회수')),
                ('qnaregdate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('repleadmin', models.CharField(max_length=50, null=True, verbose_name='답변작성자')),
                ('replecontent', models.TextField(null=True, verbose_name='답변글 내용')),
                ('repleregdate', models.DateTimeField(auto_now_add=True, verbose_name='답변 작성일')),
            ],
        ),
    ]
