# Generated by Django 4.1 on 2022-11-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppaydetail',
            name='common_door',
            field=models.CharField(default='0', max_length=1000, verbose_name='공동현관비밀번호'),
        ),
    ]
