# Generated by Django 4.1 on 2022-10-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopmember',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='아이디')),
                ('user_passwd', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('user_name', models.CharField(max_length=100, verbose_name='이름')),
                ('user_tel', models.CharField(max_length=30, verbose_name='전화번호')),
                ('user_addr', models.CharField(max_length=1000, verbose_name='주소')),
                ('user_addrt', models.CharField(max_length=1000, verbose_name='상세 주소')),
                ('user_gender', models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=100, verbose_name='성별')),
                ('user_brand', models.CharField(max_length=100, null=True, verbose_name='선호 브렌드')),
            ],
        ),
        migrations.CreateModel(
            name='Shopmemberdelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='아이디')),
                ('user_passwd', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('user_name', models.CharField(max_length=100, verbose_name='이름')),
                ('user_tel', models.CharField(max_length=30, verbose_name='전화번호')),
                ('user_addr', models.CharField(max_length=1000, verbose_name='주소')),
                ('user_addrt', models.CharField(max_length=1000, verbose_name='상세 주소')),
                ('user_gender', models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=100, verbose_name='성별')),
                ('user_brand', models.CharField(max_length=100, null=True, verbose_name='선호 브렌드')),
            ],
        ),
    ]
