# Generated by Django 4.1 on 2022-10-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmember', '0002_shopmember_user_email_shopmemberdelete_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmember',
            name='user_gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자'), ('제3의성', '제3의성')], max_length=100, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='shopmemberdelete',
            name='user_gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자'), ('제3의성', '제3의성')], max_length=100, verbose_name='성별'),
        ),
    ]
