# Generated by Django 4.1 on 2022-10-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopproduct', '0001_initial'),
        ('shopmember', '0003_alter_shopmember_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmember',
            name='user_gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=100, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='shopmemberdelete',
            name='user_gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=100, verbose_name='성별'),
        ),
        migrations.CreateModel(
            name='Shoprecome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodnum', models.ForeignKey(db_column='prodnum', on_delete=django.db.models.deletion.CASCADE, to='shopproduct.shopproduct', verbose_name='상품번호')),
            ],
        ),
    ]
