# Generated by Django 4.1 on 2022-10-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopnotice',
            fields=[
                ('noticenum', models.AutoField(primary_key=True, serialize=False, verbose_name='공지번호')),
                ('adminname', models.CharField(max_length=30, verbose_name='작성자')),
                ('noticetitle', models.CharField(max_length=200, verbose_name='글 제목')),
                ('noticecontent', models.TextField(verbose_name='글 내용')),
                ('noticereadcount', models.IntegerField(default=0, verbose_name='조회수')),
                ('noticeregdate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
