# Generated by Django 4.1 on 2022-10-05 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoppay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodreturn',
            fields=[
                ('returnnum', models.AutoField(primary_key=True, serialize=False, verbose_name='반품번호')),
                ('prodnum', models.IntegerField(verbose_name='상품번호')),
                ('prodname', models.CharField(max_length=200, verbose_name='상품이름')),
                ('user_id', models.CharField(max_length=30, verbose_name='아이디')),
                ('return_title', models.CharField(max_length=300, verbose_name='반품제목')),
                ('return_content', models.TextField(verbose_name='반품내용')),
                ('return_img', models.ImageField(upload_to='반품사진')),
                ('return_status', models.CharField(choices=[('진행중', '진행중'), ('승인', '승인'), ('불가', '불가')], default='진행중', max_length=100, verbose_name='반품승인상태')),
                ('returnadmin', models.CharField(max_length=50, null=True, verbose_name='반품답변작성자')),
                ('return_message', models.CharField(max_length=4000, verbose_name='반품불가 사유')),
                ('return_msg_regdate', models.DateTimeField(auto_now_add=True, verbose_name='관리자메세지 작성일')),
                ('return_regdate', models.DateTimeField(auto_now_add=True, verbose_name='반품작성일')),
                ('paydetailnum', models.ForeignKey(db_column='paydetailnum', on_delete=django.db.models.deletion.CASCADE, to='shoppay.shoppaydetail', verbose_name='주문번호')),
            ],
        ),
    ]
