# Generated by Django 4.1 on 2022-10-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopreview',
            fields=[
                ('reviewnum', models.AutoField(primary_key=True, serialize=False, verbose_name='리뷰 번호')),
                ('reviewtitle', models.CharField(max_length=400, verbose_name='리뷰 제목')),
                ('reviewcontent', models.CharField(max_length=4000, verbose_name='리뷰 내용')),
                ('reviewimg', models.ImageField(max_length=500, null=True, upload_to='reviewimg', verbose_name='리뷰 사진')),
                ('reviewrating', models.IntegerField(verbose_name='별점')),
                ('reviewregdate', models.DateTimeField(auto_now_add=True, verbose_name='리뷰 작성일')),
                ('prodnum', models.IntegerField(verbose_name='상품번호')),
                ('user_id', models.CharField(max_length=30, verbose_name='작성자')),
            ],
        ),
    ]
